DEBUG = True
SQL = 'mysql'
DRIVER = 'pymysql'
HOST = '127.0.0.1'
PORT = '3306'
USERNAME = 'demouser'
PASSWORD = '74108520963.ljhljh'
BASENAME = 'demodb'
CHARSET = 'utf8'
SQLALCHEMY_DATABASE_URI = f'{SQL}+{DRIVER}://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{BASENAME}?charset={CHARSET}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_KEY = 'qwertyuasdfghj'
EXPIRE_TIME = 168  # 小时
REDIS_HOST = ''
REDIS_PORT = ''
REDIS_DB = ''
REDIS_PWD = ''
